import { ref, onMounted } from 'vue'
import type { WebData } from '../types/web-data'
import { schemaSupported } from '../lib/schema'

/** Load web_data.json at runtime. No retries, no caching: the JSON is tiny
 *  and regenerated by the engine; the page is a dumb renderer of it. */
export function useHoursData() {
  const data = ref<WebData | null>(null)
  const loading = ref(true)
  const error = ref<string | null>(null)

  onMounted(async () => {
    try {
      const res = await fetch(`${import.meta.env.BASE_URL}web_data.json`)
      if (!res.ok) throw new Error(`HTTP ${res.status} fetching web_data.json`)
      const json = (await res.json()) as WebData
      const version = json?.meta?.schema_version ?? '(missing)'
      if (!schemaSupported(version)) {
        throw new Error(
          `Unsupported data schema "${version}" — this page needs schema 1.1 or later. ` +
          `Regenerate web_data.json with the current engine.`,
        )
      }
      data.value = json
    } catch (e) {
      error.value = e instanceof Error ? e.message : String(e)
    } finally {
      loading.value = false
    }
  })

  return { data, loading, error }
}
